Mitre Attack SP Update
fortinet-fortisoar/solution-mitre-attack pull request #25
Opened 2021-12-21 14:26 UTC by cs-rohit-khune

a. Added Mock Output in all the Hunt MITRE Attack Playbooks
b. Added new playbooks to link 'Techniques' and 'Sub-Techniques' on update of MITRE ATTACK ID field
c. Updated logic to fetch comments corelated to hunt record in playbook " 13 - MITRE ATT&CK™ - Modulars > Deduplicate Comments (Hunt)"

UT Steps:
  1. Execute playbook from Hunt record for specific MITRE Attack
  2. Choose SIEM from manual decision pop-up e.g Elastic
  3. Validate if alert is created for MITRE Attack ID
  4. Validate if alert is linked to corresponding MITRE Attack technique or sub-technique
  5. Validate if comments relavent to alert has been added in Hunt record
  6. Validate if duplicate comments has been deleted by comment deduplication playbook

2021-12-21 16:23 UTC, cs-priyank-mankad approved these changes
LGTM

2021-12-21 18:03 UTC, cs-suyog-jinturkar requested changes
Please look at the review comments.

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Access Token Manipulation/HUNTS - SID-History Injection (T1134.005).json
> +                "version": "2.2.1",
Why we changed the connector version here? Have we tested with this connector?

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Access Token Manipulation/HUNTS - SID-History Injection (T1134.005).json
> +    "isActive": true,
Why it was deactivate earlier and activated now?

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Access Token Manipulation/HUNTS - SID-History Injection (T1134.005).json
> +                "mock_result": "{\n  \"data\": {\n    \"hits\": {\n      \"hits\": [\n        {\n          \"_id\": \"weOluGsBiKk7UqmIGjOt\",\n          \"_type\": \"doc\",\n          \"_index\": \"l
Just want to confirm that, it has does not contain any customer data or customer specific details?

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Boot or Logon Autostart Execution/HUNTS - Winlogon Helper DLL (T1547.004).json
> +    "isActive": true,
same as above

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Boot or Logon Autostart Execution/HUNTS - Winlogon Helper DLL (T1547.004).json
> +                "mock_result": "{\n  \"data\": {\n    \"hits\": {\n      \"hits\": [\n        {\n          \"_id\": \"5bQvr2sBt8nuALoCXeGH\",\n          \"_type\": \"doc\",\n          \"_index\": \"l
same as above

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Credential Access/HUNTS - OS Credential Dumping (T1003) Part2.json
> -                            "processID": "{{ vars.processID }}",
Why we removed this?

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Credential Access/HUNTS - OS Credential Dumping (T1003).json
> +    "isActive": true,
same as above

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Link Techniques to Alerts and Incidents/Link ATT&CK technique to Alert.json
> +    "description": "Links MITRE technique or sub-technique to Alert, based on MITRE Attack ID",
to an alert,

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Link Techniques to Alerts and Incidents/Link ATT&CK technique to Alert.json
> +    "isActive": true,
same as above? why activated now?

2021-12-21 18:03 UTC, cs-suyog-jinturkar commented on playbooks/13 - MITRE ATT&CK - Link Techniques to Alerts and Incidents/Link ATT&CK technique to Incident (On Update).json
> +    "description": "Links MITRE technique or sub-technique to Incident, based on MITRE Attack ID",
to an incident

2021-12-22 05:31 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Access Token Manipulation/HUNTS - SID-History Injection (T1134.005).json
> +                "version": "2.2.1",
This seems to be changed automatically, the old playbooks were built using v2.2.0 and the latest Mitre attack SP installs Elasticsearch v2.2.1 connector. Yes, all the testing has been done v2.2.1

2021-12-22 05:36 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Access Token Manipulation/HUNTS - SID-History Injection (T1134.005).json
> +    "isActive": true,
These playbooks are manually triggered on Hunt record, in order to make it visible in the "Execute" button, hence activating the playbook.

2021-12-22 05:36 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Boot or Logon Autostart Execution/HUNTS - Winlogon Helper DLL (T1547.004).json
> +    "isActive": true,
These playbooks are manually triggered on Hunt record, in order to make it visible in the "Execute" button, hence activating the playbook.

2021-12-22 05:37 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Credential Access/HUNTS - OS Credential Dumping (T1003).json
> +    "isActive": true,
These playbooks are manually triggered on Hunt record, in order to make it visible in the "Execute" button, hence activated the playbooks.

2021-12-22 05:42 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Link Techniques to Alerts and Incidents/Link ATT&CK technique to Alert.json
> +    "isActive": true,
This is the 'Post Create' triggered on the alert record, hence activating the playbook. 
Note: The trigger condition checks if the MITRE ATT&CK ID field is populated or not. So this playbook triggers only mitre related alerts

2021-12-22 06:33 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Credential Access/HUNTS - OS Credential Dumping (T1003) Part2.json
> -                            "processID": "{{ vars.processID }}",
This was automatically removed, I am investigating this. However, this has no impact on playbook operation.

2021-12-22 06:41 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Link Techniques to Alerts and Incidents/Link ATT&CK technique to Alert.json
> +    "description": "Links MITRE technique or sub-technique to Alert, based on MITRE Attack ID",
I have changed the description to "Links MITRE technique or sub-technique to an alert, based on MITRE Attack ID"

2021-12-22 06:42 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Link Techniques to Alerts and Incidents/Link ATT&CK technique to Incident (On Update).json
> +    "description": "Links MITRE technique or sub-technique to Incident, based on MITRE Attack ID",
updated playbook description to "Links MITRE technique or sub-technique to an incident, based on MITRE Attack ID"

2021-12-22 07:06 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Boot or Logon Autostart Execution/HUNTS - Winlogon Helper DLL (T1547.004).json
> +                "mock_result": "{\n  \"data\": {\n    \"hits\": {\n      \"hits\": [\n        {\n          \"_id\": \"5bQvr2sBt8nuALoCXeGH\",\n          \"_type\": \"doc\",\n          \"_index\": \"l
found some references for Cybercom, updated the same from all the playbooks by removing the references

2021-12-22 07:06 UTC, cs-rohit-khune commented on playbooks/13 - MITRE ATT&CK - Access Token Manipulation/HUNTS - SID-History Injection (T1134.005).json
> +                "mock_result": "{\n  \"data\": {\n    \"hits\": {\n      \"hits\": [\n        {\n          \"_id\": \"weOluGsBiKk7UqmIGjOt\",\n          \"_type\": \"doc\",\n          \"_index\": \"l
found some references for Cybercom, updated the same from all the playbooks by removing the references

2021-12-22 11:06 UTC, merged